name: google_map_location_picker
description: 'ðŸŒ Map location picker for flutter Based on google_maps_flutter'
version: 3.3.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0 <=1.0.0'
  intl_translation: '>=0.17.10 <=1.0.0'
  flutter_keyboard_visibility: ^5.0.0-nullsafety.1
  # google_maps_flutter: '>=0.5.27 <=1.0.0'
  google_maps_flutter: '>=1.2.0 <=2.0.0'
  geolocator: '>=6.2.0 <=7.0.0'
  android_intent: '>=0.3.7+1 <=1.0.0'
  provider: '>=4.0.5+1 <=5.0.0'
  http: '>=0.12.1 <=1.0.0'
  stack_trace: '>=1.9.3 <=2.0.0'
  package_info: '>=0.4.0+14 <2.0.0'

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.humazed.google_map_location_picker
    pluginClass: GoogleMapLocationPickerPlugin